version: "3.9"

services:
  auth:
    image: authelia/authelia:4.38
    container_name: authelia
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./config:/config
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.rule=Host(`auth.jxlxx.org`)"
      - "traefik.http.routers.auth.entrypoints=websecure"
      - "traefik.http.routers.auth.tls.certresolver=le"
      - "traefik.http.services.auth.loadbalancer.server.port=9091"

networks:
  proxy:
    external: true
