version: "3.9"

services:
  synapse:
    image: matrixdotorg/synapse:latest
    container_name: synapse
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - synapse-db
    volumes:
      - synapse-data:/data
      - ./config/homeserver.yaml:/data/homeserver.yaml:ro
      - ./config/log.config:/data/log.config:ro
    networks:
      - proxy
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.matrix.rule=Host(`matrix.jxlxx.org`)"
      - "traefik.http.routers.matrix.entrypoints=websecure"
      - "traefik.http.routers.matrix.tls.certresolver=le"
      - "traefik.http.routers.matrix.middlewares=authelia-auth@file"
      - "traefik.http.services.matrix.loadbalancer.server.port=8008"

  synapse-db:
    image: postgres:15-alpine
    container_name: synapse-db
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - synapse-db-data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d:ro
    networks:
      - internal

volumes:
  synapse-data:
    name: matrix_synapse-data
  synapse-db-data:
    name: matrix_synapse-db-data

networks:
  proxy:
    external: true
  internal:
    internal: true
