version: "3.9"

services:
  home:
    image: nginx:1.25-alpine
    container_name: home-site
    restart: unless-stopped
    volumes:
      - ./html:/usr/share/nginx/html:ro
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.home.rule=Host(`home.jxlxx.org`)"
      - "traefik.http.routers.home.entrypoints=web"
      # - "traefik.http.routers.home.entrypoints=websecure"
      # - "traefik.http.routers.home.tls.certresolver=le"
      # - "traefik.http.routers.home.middlewares=authelia-auth@file"
      - "traefik.http.services.home.loadbalancer.server.port=80"

networks:
  proxy:
    external: true
